version: '3'
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./backend-user
    image: backend-user
  backend_feed:
    build:
      context: ./backend-feed
    image: backend-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
