apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user-srv
  labels:
    run: udagram-api-user-srv
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: udagram-api-user-srv
