apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: udagram-api-user
          image: unicdev/udagram-api-user:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
          env:
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_BUCKET

            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_HOST

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_DB

            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_REGION

            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: AWS_PROFILE

            - name: URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET

            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
