apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-srv
  labels:
    run: udagram-frontend-srv
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: udagram-frontend-srv
